name: journey2europe
description: Offline document expiration manager

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.0.3

flutter:
  uses-material-design: true
